baseURL: https://claireboyd.github.io/
languageCode: en
DefaultContentLanguage: en
title: Claire
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
params:
  author: Claire
  customCss: []
  customJs: []
  description: Call me Jane
  doNotLoadAnimations: no
  favicon: favicons/
  images: images/site-feature-image.png
  keywords: ''
  mainSections: post
  math:
    enable: no
    use: katex
  profilePicture: images/profile.jpg
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/claire-boyd/
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/claireboyd
    - icon: fab fa-twitter
      title: twitter
      url: https://twitter.com/clairekboyd
    - icon: fas fa-envelope
      title: e-mail
      url: mailto:claire.k.boyd@gmail.com
  title: Claire Boyd
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 100
    - identifier: posts
      name: Posts
      url: /post/
      weight: 200
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 300
   # - identifier: contact
   #   name: Contact
   #   url: /contact/
   #   weight: 400
